#test
name: my workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Read version
      id: package
      uses: juliangruber/read-file-action@v1
      with:
        path: ./pom.xml
    - name: Echo version
      run: |
             version=$(echo ${{ steps.package.outputs.content }} ) 
             #| grep Version | awk -F> '{print $2}' | awk -F< '{print $2}')
             echo $version  

